# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Et48WDF3c4YLOcf04diHrgfivVBVzJR0
"""

import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense


training_data = np.array([[1,1,1,1], [0,1,1,1], [1,1,0,0], [0,0,0,0],[1,0,1,1],[1,1,0,1],[1,1,1,0]], np.int)


target_data = np.array([[0,0],[0,1],[1,0],[1,1],[1,0],[0,1],[1,0]],np.int)

model = Sequential()
model.add(Dense(2, input_dim=4, activation='sigmoid'))
#model.add(Dense(2, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, nb_epoch=2000, verbose=2)

x_test = np.array([[0,0,1,0]],np.int)
classes=[]
classes = model.predict(x_test, batch_size=200)
print(x_test)
print(classes)